resources:
- name: repo
  type: git
  source:
    uri: git@github.com:ashidubey/spring-boot-example.git
    branch: production
    private_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACDUJGk3QdtO9XiDzPzlf54wmQfsVcMmcCtRaoZQsQMlmgAAAJA6YncpOmJ3
      KQAAAAtzc2gtZWQyNTUxOQAAACDUJGk3QdtO9XiDzPzlf54wmQfsVcMmcCtRaoZQsQMlmg
      AAAEDPyh/9SgYoJeeY1mnzFmB53rneXqzasR+WOGpekSLj0tQkaTdB2071eIPM/OV/njCZ
      B+xVwyZwK1FqhlCxAyWaAAAAC2plbmtpbnMga2V5AQI=
      -----END OPENSSH PRIVATE KEY-----

- name: maven-image
  type: docker-image
  source:
    repository: maven
    tag: 3.6.0-jdk-8-alpine
   

jobs:
- name: product
  plan:
    - get: maven-image
    - get: repo
      trigger: true
    - task: test
      image: maven-image
      config:
        platform: linux
        inputs: [name: repo]
        run:
          path: sh
          args:
          - -c
          - |
            mvn clean
            mvn compile
            mvn test
          dir: repo   


